name: mad2_browsepage
description: Adds an event for MAD 2.0.
version: 1.0.0+4
repository: https://github.com/MahirEmran/MAD2_BrowsePage.git

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  easy_debounce: 2.0.1
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 3.0.1
  intl: 0.17.0
  json_path: 0.4.1
  page_transition: 2.0.4
  shared_preferences: 2.0.15
  sqflite: 2.2.0+2
  timeago: 3.2.2
  url_launcher: 6.1.5
  fluttertoast: ^8.1.1
  mad2_db_dataobjects: ^1.0.0+1
  mad2_addevent: ^1.0.1+6







dev_dependencies:

  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Medium.ttf
        - asset: assets/Montserrat-SemiBold.ttf  
        - asset: assets/Montserrat-Bold.ttf
        - asset: assets/Montserrat-ExtraBold.ttf    
  
  