name: mad2_browsepage
description: JagHub browsing page for FBLA's Coding and Programming event. 2022-23.
version: 1.6.2
repository: https://github.com/MahirEmran/JagHub_Browse.git

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: 0.17.0

  url_launcher: 6.1.5
  fluttertoast: ^8.1.1
  mad2_db_dataobjects: ^1.1.0
  mad2_leaderboard: ^1.1.9
  mad2_shop: ^1.1.0
  mad2_login: ^1.0.3
  easy_debounce: ^2.0.2+1

dev_dependencies:

  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Medium.ttf
        - asset: assets/Montserrat-SemiBold.ttf  
        - asset: assets/Montserrat-Bold.ttf
        - asset: assets/Montserrat-ExtraBold.ttf    
  
  